[package]
edition = "2021"
name = "stream-download"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
bytes = "1"
futures = "0.3"
parking_lot = "0.12"
rangemap = "1"
reqwest = { version = "0.11", default-features = false, features = [
    "stream",
], optional = true }
tap = "1"
tempfile = "3"
tokio = { version = "1", features = ["sync", "macros", "rt"] }
tokio-util = "0.7"
tracing = "0.1"

[features]
default = ["http"]
http = ["reqwest"]
http-native-tls = ["reqwest/native-tls"]
http-rustls = ["reqwest/rustls-tls"]

[dev-dependencies]
rodio = { version = "0.17.1", default-features = false, features = [
    "symphonia-all",
] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread"] }


[[example]]
name = "stream"
required-features = ["http-rustls"]
