[package]
edition = "2021"
name = "stream-download"
version = "0.1.0"

[dependencies]
async-trait = "0.1.9"
bytes = "1"
futures = "0.3"
# reqwest fails to compile on log < 0.4.6
log = "0.4.6"
parking_lot = "0.12.1"
rangemap = "1"
# reqwest 0.11.10 fixes serde_urlencoded dependency version which had incorrect serde dependency
reqwest = { version = "0.11.10", features = [
    "stream",
], default-features = false, optional = true }
tap = "1.0.1"
tempfile = "3"
tokio = { version = "1", features = ["sync", "macros", "rt"] }
tokio-util = "0.7"
tracing = "0.1.37"

[features]
default = ["reqwest"]
http = []
reqwest = ["http", "dep:reqwest"]
reqwest-native-tls = ["reqwest", "reqwest/native-tls"]
reqwest-rustls = ["reqwest", "reqwest/rustls-tls"]

[dev-dependencies]
rodio = { version = "0.17.1", default-features = false, features = [
    "symphonia-all",
] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread"] }
tower-http = { version = "0.4.3", features = ["fs"] }
hyper = { version = "0.14.27", features = ["server"] }
tower = { version = "0.4.13", features = ["make"] }
ctor = "0.2.4"
rstest = "0.18.1"


[[example]]
name = "stream"
required-features = ["reqwest-rustls"]
