on: [push]
name: CI
env:
  BINSTALL_VERSION: 1.1.2
  RUST_MIN: 1.63

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - name: Minimal build
        run: cargo build --no-default-features
      - name: Clippy
        run: |
          # TODO finish docs and re-enable
          # cargo clippy --all-features -- -D warnings
          cargo clippy --all-features
      - name: Build all
        run: cargo build --all-features --examples
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Test
        run: |
          cargo test --doc
          cargo llvm-cov nextest --all-features --codecov --ignore-filename-regex ".cargo|.*_test\.rs" > ./codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          fail_ci_if_error: true
          files: ./codecov.json

  min-versions:
    name: Check min dependency versions
    # newer ubuntu versions have problems with older versions of openssl-sys
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Install cargo-minimal-versions
        uses: taiki-e/install-action@cargo-minimal-versions
      - name: Cargo minimal-versions
        run: |
          cargo minimal-versions check --no-default-features
          cargo minimal-versions check
          cargo minimal-versions check --all-features

  min-rust:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ env.RUST_MIN }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_MIN }}
      - uses: Swatinem/rust-cache@v2
      - name: Cargo check
        run: cargo check --workspace --all-features
