on: [push]
name: CI
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cache-${{ hashFiles('**/Cargo.toml') }}
      - name: Install dependencies
        run: sudo apt-get install -y libasound2-dev
      - name: Minimal build
        run: cargo build --no-default-features
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
      - name: Build all
        run: cargo build --all-features --examples
      - name: Test
        run: |
          cargo install cargo-llvm-cov
          cargo llvm-cov --all-features --codecov --ignore-filename-regex ".cargo|.*_test\.rs" > ./codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          fail_ci_if_error: true
          files: ./codecov.json
